[package]
name = "mv5t"
version = "0.1.0"
authors = ["Phoenix <kahlo.phoenix@gmail.com>"]

[dependencies]
file = "1.1.1"
oauth-client = "0.3.2"
yandex_translate = "2.1.0"
json = "0.11.13"
regex = "0.2.10"
